# Generated by Django 5.2 on 2025-04-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card_no', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('iqama_id', models.CharField(max_length=20)),
                ('certified_level', models.CharField(max_length=50)),
                ('model_level', models.CharField(max_length=50)),
                ('issued_on', models.DateField()),
                ('valid_until', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
